[project]
name = "variation-antimicrobial-consumption-in-critically-ill-adults"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clifpy>=0.1.0",
]
